Add initial docs about backup processes
MozillaFoundation/MoFo-Engineering-Handbook pull request #53
Opened 2021-09-16 08:35 UTC by tomusher

2021-09-16 15:16 UTC, Pomax requested changes

2021-09-16 15:16 UTC, Pomax commented on docs/services/backups.md
> +3. Upload the downloaded file to an encrypted S3 bucket - don't forget to rename the file to something more descriptive.
I think it's probably fine to say which location we want backups saved to, or link to a doc in our private devops repo that says which S3 location to use so that we don't end up with people putting backups in disparate locations.

2021-09-16 16:40 UTC, Pomax approved these changes

2021-09-20 13:52 UTC, benhohner approved these changes
Looks great

2021-09-20 13:52 UTC, merged